
const q=new URLSearchParams(location.search), id=q.get('id'), list=Array.isArray(window.COLLEGES)?window.COLLEGES:[], c=list.find(x=>x.id===id)||list[0], p=c?.profile||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=v=>typeof v==='number'?v.toFixed(2):'—';
const rows=(c.cutoffs||[]).filter(x=>[3,4,5,6].some(i=>typeof x[i]==='number'));
const branchSet=[...new Set((c.branches||[]).map(String))];
const values=rows.flatMap(x=>[3,4,5,6].map(i=>x[i]).filter(v=>typeof v==='number'));
const min=values.length?Math.min(...values):null,max=values.length?Math.max(...values):null;
const sourceList=Array.isArray(p.sources)?p.sources:[];
const sourceLinks=sourceList.map((u,i)=>`<a href="${esc(u)}" target="_blank" rel="noopener">Official source ${i+1} ↗</a>`).join('');
const cutoffRows=rows.map(x=>`<tr><td>${esc(x[0])}</td><td>${esc(x[1])}</td><td>${esc(x[2])}</td><td>${num(x[6])}</td><td>${num(x[5])}</td><td>${num(x[4])}</td><td>${num(x[3])}</td></tr>`).join('');

document.title=(c.shortName||c.name)+' - MahaCollege';
document.getElementById('details').innerHTML=`
<a class="back" href="college-predictor.html">← Back to College Predictor</a>
<section class="hero-card"><h1>🎓 ${esc(c.name)}</h1><p class="hero-meta">📍 ${esc(c.city)}, ${esc(c.district)}, Maharashtra · Region: ${esc(c.region)}</p><p class="hero-meta">Institute Code: <strong>${esc(c.id)}</strong> · Status: <strong>${esc(c.status)}</strong> · University/Affiliation: <strong>${esc(c.university)}</strong></p><div class="badges">${branchSet.map(b=>`<span>${esc(b)}</span>`).join('')}</div><p style="margin-top:15px">${esc(p.overview||'This college is listed in the Maharashtra State CET Cell 2026-27 participating institute directory. The fields below are based on the project dataset and official admission sources.')}</p><div class="links"><a href="${esc(p.cetProfile||('https://fe2026.mahacet.org/StaticPages/frmInstituteSummary?InstituteCode='+c.id))}" target="_blank" rel="noopener">Official CET Cell Institute Profile ↗</a>${p.officialWebsite?`<a href="${esc(p.officialWebsite)}" target="_blank" rel="noopener">Official College Website ↗</a>`:''}</div></section>

<section class="details-section"><h2>College at a glance</h2><div class="stat-grid"><div class="stat"><b>${esc(c.totalIntake||'—')}</b>2026-27 total intake</div><div class="stat"><b>${branchSet.length}</b>listed branches</div><div class="stat"><b>${rows.length}</b>cutoff rows loaded</div><div class="stat"><b class="verified">Verified</b>CET directory identity</div></div></section>

<section class="details-section"><h2>Institute information</h2><div class="profile-grid"><div class="profile-item"><h3>🏛️ Institute type / status</h3><p>${esc(c.status)}</p></div><div class="profile-item"><h3>🎓 University / affiliation</h3><p>${esc(c.university)}</p></div><div class="profile-item"><h3>📍 Location</h3><p>${esc(c.city)}, ${esc(c.district)}, Maharashtra</p></div><div class="profile-item"><h3>💺 Approved total intake</h3><p>${esc(c.totalIntake||'Not available in loaded directory')}</p></div><div class="profile-item"><h3>📚 Courses / branches</h3><p>${branchSet.length} branches are included in this predictor dataset.</p></div><div class="profile-item"><h3>📝 Admission route</h3><p>B.E./B.Tech admissions use the Maharashtra State CET Cell CAP process; exact eligibility, seat matrix and current notices should be checked for the admission year.</p></div></div></section>

<section class="details-section"><h2>📚 All branches</h2><ul class="branch-list">${branchSet.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></section>

<section class="details-section"><h2>📊 2026-27 CAP cutoff data</h2><div class="cutoff-summary"><div class="summary-box"><b>${min===null?'—':min.toFixed(2)}</b>Lowest loaded cutoff percentile</div><div class="summary-box"><b>${max===null?'—':max.toFixed(2)}</b>Highest loaded cutoff percentile</div><div class="summary-box"><b>${rows.length}</b>verified cutoff rows in dataset</div></div><p class="source">CAP 1–4 values below are shown exactly from the loaded project cutoff rows. A dash means no numeric value is present for that exact row/round.</p><div class="table-wrap"><table><thead><tr><th>Branch</th><th>Category</th><th>Seat pool</th><th>CAP 1</th><th>CAP 2</th><th>CAP 3</th><th>CAP 4</th></tr></thead><tbody>${cutoffRows||'<tr><td colspan="7">No numeric cutoff rows loaded for this college.</td></tr>'}</tbody></table></div><div class="links"><a href="https://cappublicdocs2026.blob.core.windows.net/documents/2026ENGG_CAP1_MH_CutOff_V1.pdf" target="_blank" rel="noopener">Official CAP 1 Cutoff ↗</a><a href="https://cappublicdocs2026.blob.core.windows.net/documents/2026ENGG_CAP2_MH_CutOff.pdf" target="_blank" rel="noopener">Official CAP 2 Cutoff ↗</a><a href="https://cappublicdocs2026.blob.core.windows.net/documents/2026ENGG_CAP3_MH_CutOff.pdf" target="_blank" rel="noopener">Official CAP 3 Cutoff ↗</a><a href="https://cappublicdocs2026.blob.core.windows.net/documents/2026ENGG_CAP4_MH_CutOff.pdf" target="_blank" rel="noopener">Official CAP 4 Cutoff ↗</a></div></section>

<section class="details-section"><h2>🏫 Campus, facilities, faculty & placements</h2>${p.campus||p.facilities||p.faculty||p.placements?`<div class="profile-grid"><div class="profile-item"><h3>🏫 Campus</h3><p>${esc(p.campus||'Not published in the loaded profile.')}</p></div><div class="profile-item"><h3>🔬 Facilities</h3><p>${esc(p.facilities||'Not published in the loaded profile.')}</p></div><div class="profile-item"><h3>👨‍🏫 Faculty</h3><p>${esc(p.faculty||'Not published in the loaded profile.')}</p></div><div class="profile-item"><h3>💼 Placements</h3><p>${esc(p.placements||'Not published in the loaded profile.')}</p></div><div class="profile-item"><h3>🌿 Environment</h3><p>${esc(p.environment||'Not published in the loaded profile.')}</p></div><div class="profile-item"><h3>🏅 Accreditation</h3><p>${esc(p.accreditation||'Check the current official disclosure.')}</p></div></div>`:`<div class="notice">Detailed campus, faculty, facility and placement figures are not present in the Maharashtra CET Cell directory data used by this project, so no figures are invented here. Use the official institute profile/website for the current details.</div>`}</section>

<section class="details-section"><h2>💰 Fees & admission documents</h2><div class="profile-grid"><div class="profile-item"><h3>Fees</h3><p>${esc(p.fees||'Current approved fees should be checked against the Maharashtra Fees Regulating Authority notice for the relevant academic year.')}</p></div><div class="profile-item"><h3>CAP / admission</h3><p>${esc(p.admission||'Check the Maharashtra CET Cell CAP portal for registration, merit lists, seat matrix, allotment and cutoffs.')}</p></div></div><div class="links"><a href="https://cetcell.mahacet.org/cap-_2025-26/" target="_blank" rel="noopener">Maharashtra CET Cell CAP Portal ↗</a><a href="https://ay26-27.mahafraportal.org/" target="_blank" rel="noopener">Fees Regulating Authority ↗</a></div></section>

<section class="details-section"><h2>🔗 Official sources</h2><p class="source">${esc(typeof DATA_SOURCE!=='undefined'?DATA_SOURCE:'Maharashtra State CET Cell — Institute directory')}</p><div class="links">${sourceLinks||`<a href="${esc(p.cetProfile||('https://fe2026.mahacet.org/StaticPages/frmInstituteSummary?InstituteCode='+c.id))}" target="_blank" rel="noopener">Official CET Cell Institute Profile ↗</a>`}</div><div class="notice" style="margin-top:12px"><strong>Data note:</strong> CAP intake/status and cutoff information is admission-cycle data and can change for a new academic year. College-specific placement, fee, accreditation and facility claims are shown only where the project has a verified source; otherwise the official source is provided instead of fabricated figures.</div></section>`;
